<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUjtfFf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUjtfFf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJUjtfFf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJUjtfFf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJUjtfFf\App_KernelDevDebugContainer([
    'container.build_hash' => 'JUjtfFf',
    'container.build_id' => '0f254fea',
    'container.build_time' => 1607644075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUjtfFf');
